### ISSUE TITLE
[issue-1] 프로젝트 환경 구성

### ISSUE THREAD

**Issue by prebird** [f-lab-edu/kyumall#1]
## 개요
kyumall(쇼핑몰 서비스)를 위한 백엔드 프로젝트를 생성합니다. 멀티 모듈로 나누어 구성합니다.

## 내용
현재 프로젝트의 규모가 크지 않기 때문에 복잡한 모듈 구조를 설계할 필요는 없다고 생각했고, 아래와 같이 3가지 모듈로 나누어 설계하였습니다.

<img width="682" alt="image" src="https://github.com/f-lab-edu/kyumall/assets/78974381/196ab4cd-f628-4b6e-b5ea-b434e25e10c4">

- Client용 모듈 : 유저들에게 서비스하기 위한 모듈
- Admin용 모듈 : 관리자를 위한 모듈
- 공통 모듈 : 도메인, 공통 로직들을 위한 모듈

**Comment by f-lab-paul** [comment]
@prebird 문서화 훌륭합니다.
제목에 [issue-1] 이런식으로 태깅해주시고, 커밋시에도 위에 태깅 내용을 같이 적어주시면 파악이 쉽습니다.

**Comment by prebird** [comment]
> @prebird 문서화 훌륭합니다. 제목에 [issue-1] 이런식으로 태깅해주시고, 커밋시에도 위에 태깅 내용을 같이 적어주시면 파악이 쉽습니다.

네 감사합니다 수정하였습니다
