### ISSUE TITLE
약관 어드민 추가

### ISSUE THREAD

**Issue by prebird** [f-lab-edu/kyumall#17]
## admin 개발준비
- 어드민에도 공통으로 쓰이는 클래스를 공통 모듈로 이동합니다.
- `exception`, `response` 모듈 이동 (`kyumall-client` -> `kyumall-common`)

## 약관 CRUD
1. 약관 추가
2. 약관 수정
3. 약관 이름으로 조회

## 약관 상세 CRUD
1. 약관 상세 추가
2. 약관 상세 수정
3. 약관 상세 조회 (약관으로)

## 약관 Admin UI
<img width="543" alt="image" src="https://github.com/f-lab-edu/kyumall/assets/78974381/1280d972-b5e3-45ba-bf40-5f6db55b350a">

**Comment by f-lab-paul** [comment]
코멘트 남겼어요. 내일 멘토링때 봐요
